version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
      - ../config/keys/:/keys/
    networks:
      default:
        aliases:
          - dixidex.com
          - auth.dixidex.com
          - ws.dixidex.com
          - pma.dixidex.com
          - monitor.dixidex.com
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.dixidex.com'
      traefik.port: 8080
