- id:                     usd
  symbol:                 '$'
  type:                   fiat
  precision:              2
  base_factor:            1
  enabled:                true
  min_deposit_amount:     0
  min_collection_amount:  0
  withdraw_limit_24h:     100
  withdraw_limit_72h:     200
  deposit_fee:            0
  withdraw_fee:           0

- id:                     dxc
  blockchain_key:         DXC
  symbol:                 'D'
  type:                   coin
  precision:              8
  base_factor:            100_000_000
  enabled:                true
  min_deposit_amount:     0.0000356
  min_collection_amount:  0.0000356
  withdraw_limit_24h:     0.1
  withdraw_limit_72h:     0.2
  deposit_fee:            0
  withdraw_fee:           0
  options:
    case_sensitive:                   true
    min_confirmations:                1
    supports_cash_addr_format:        false
    supports_hd_protocol:             true
    allow_multiple_deposit_addresses: false
    api_client: BTC
    json_rpc_endpoint:        http://dixicoinrpc:9b1x2PPEgvGUyaSASfW4B1tmcb4ZAyt63UQQmPAobRX3@108.61.190.136:61150
    wallet_url_template:      http://www.dixi.live/address/#{address}
    transaction_url_template: http://www.dixi.live/tx/#{txid}
