- name:             Dixicoin Deposit Wallet
  blockchain_key:   DXC
  currency_id:      dxc
  address:          'DU9gxQkcU9GR7MPfGYDcnuSmLTXVMdD7FL'
  kind:             deposit
  nsig:             1
  max_balance:      0.0
  status:           active
  gateway:          dixicoind
  settings:
    uri:            http://dixicoinrpc:9b1x2PPEgvGUyaSASfW4B1tmcb4ZAyt63UQQmPAobRX3@108.61.190.136:61150

- name:             Dixicoin Hot Wallet
  blockchain_key:   DXC
  currency_id:      dxc
  address:          'DU9gxQkcU9GR7MPfGYDcnuSmLTXVMdD7FL'
  kind:             hot
  nsig:             1
  max_balance:      100.0
  status:           active
  gateway:          dixicoind
  settings:
    uri:            http://dixicoinrpc:9b1x2PPEgvGUyaSASfW4B1tmcb4ZAyt63UQQmPAobRX3@108.61.190.136:61150
